-- online
-- create tables
-- https://www.oracle.com/database/technologies/appdev/quickstartnodeonprem.html
-- https://www.npmjs.com/package/oracledb

-- drop database if exists weaponid;
-- create database if not exists weaponid;


--done
CREATE TABLE users(
     id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY ,
     name varchar2(1000) NOT NULL UNIQUE,
     username varchar2(1000) NOT NULL UNIQUE,
     password varchar2(1000) NOT NULL,
     roles VARCHAR2(1000)  DEFAULT '[]' NOT NULL,
     status NUMBER(1) DEFAULT 1 NOT NULL ,
     created_at TIMESTAMP  DEFAULT SYSDATE  NOT NULL ,
     created_by NUMBER ,
     FOREIGN KEY (created_by) REFERENCES users(id)
)
;
--ahmed
--done
create table approval_type (
    apptype_id                     varchar2(36) PRIMARY KEY NOT NULL,
    apptype                        varchar2(100) not null,
    created_at                     TIMESTAMP  DEFAULT SYSDATE  NOT NULL ,
    created_by                     NUMBER,
    updated_at                     TIMESTAMP  DEFAULT SYSDATE  NOT NULL ,
    updated_by                     NUMBER,
    FOREIGN KEY (created_by) REFERENCES users(id),
    FOREIGN KEY (updated_by) REFERENCES users(id)
)
;
--done
create table approval_weapon (
    appweap_id                             varchar2(36)  PRIMARY KEY NOT NULL,
    appweap                        varchar2(100) not null,
    created_at                     TIMESTAMP  DEFAULT SYSDATE  NOT NULL ,
    created_by                     NUMBER,
    updated_at                     TIMESTAMP  DEFAULT SYSDATE  NOT NULL ,
    updated_by                      NUMBER,
    FOREIGN KEY (created_by) REFERENCES users(id),
    FOREIGN KEY (updated_by) REFERENCES users(id)
)
;
--done
create table Category  (
    cat_Id                         varchar2(36) PRIMARY KEY NOT NULL,
    cat                            varchar2(100) not null,
    created_at                     TIMESTAMP  DEFAULT SYSDATE  NOT NULL ,
    created_by                     NUMBER,
    updated_at                     TIMESTAMP  DEFAULT SYSDATE  NOT NULL ,
    updated_by                      NUMBER,
    FOREIGN KEY (created_by) REFERENCES users(id),
    FOREIGN KEY (updated_by) REFERENCES users(id)
)
;

--done
create table Possession (
    poss_id                    varchar2(36) PRIMARY KEY NOT NULL,
    poss                  varchar2(100) not null,
    created_at                     TIMESTAMP  DEFAULT SYSDATE  NOT NULL ,
    created_by                     NUMBER,
    updated_at                     TIMESTAMP  DEFAULT SYSDATE  NOT NULL ,
    updated_by                      NUMBER,
    FOREIGN KEY (created_by) REFERENCES users(id),
    FOREIGN KEY (updated_by) REFERENCES users(id)
)
;

create table  license_type (
    license_id                        varchar2(36) PRIMARY KEY NOT NULL,
    license                     varchar2(100) not null,
    created_at                     TIMESTAMP  DEFAULT SYSDATE  NOT NULL ,
    created_by                     NUMBER,
    updated_at                     TIMESTAMP  DEFAULT SYSDATE  NOT NULL ,
    updated_by                      NUMBER,
    FOREIGN KEY (created_by) REFERENCES users(id),
    FOREIGN KEY (updated_by) REFERENCES users(id)
)
;

create table province (
    pro_id                         varchar2(36) PRIMARY KEY NOT NULL,
    pro                            varchar2(100) not null,
    created_at                     TIMESTAMP  DEFAULT SYSDATE  NOT NULL ,
    created_by                     NUMBER,
    updated_at                     TIMESTAMP  DEFAULT SYSDATE  NOT NULL ,
    updated_by                      NUMBER,
    FOREIGN KEY (created_by) REFERENCES users(id),
    FOREIGN KEY (updated_by) REFERENCES users(id)
)
;
-- ali
--done
create table gender (
    gen_id                             varchar2(36) PRIMARY KEY NOT NULL,
    gen                            varchar2(100) not null,
    created_at                     TIMESTAMP  DEFAULT SYSDATE  NOT NULL ,
    created_by                     NUMBER,
    updated_at                     TIMESTAMP  DEFAULT SYSDATE  NOT NULL ,
    updated_by                      NUMBER,
    FOREIGN KEY (created_by) REFERENCES users(id),
    FOREIGN KEY (updated_by) REFERENCES users(id)
)
;
--done
create table weapon_name (
    weapon_id                    varchar2(36) PRIMARY KEY NOT NULL,
    weapon_name                  varchar2(100) not null,
    weapon_size                  varchar2(100) not null,
    created_at                     TIMESTAMP  DEFAULT SYSDATE  NOT NULL ,
    created_by                     NUMBER,
    updated_at                     TIMESTAMP  DEFAULT SYSDATE  NOT NULL ,
    updated_by                      NUMBER,
    FOREIGN KEY (created_by) REFERENCES users(id),
    FOREIGN KEY (updated_by) REFERENCES users(id)
)
;
--done
create table Issuer (
    iss_id                         varchar2(36) PRIMARY KEY NOT NULL,
    Iss                            varchar2(200) not null,
    created_at                     TIMESTAMP  DEFAULT SYSDATE  NOT NULL ,
    created_by                     NUMBER,
    updated_at                     TIMESTAMP  DEFAULT SYSDATE  NOT NULL ,
    updated_by                      NUMBER,
    FOREIGN KEY (created_by) REFERENCES users(id),
    FOREIGN KEY (updated_by) REFERENCES users(id)
)
;

--done
create table requests (
    id                          varchar2(36) PRIMARY KEY NOT NULL ,
    name1                       varchar2(100) Not Null,
    name2                       varchar2(100) Not Null,
    name3                       varchar2(100) Not Null,
    name4                       varchar2(100) Not Null,
    surname                     varchar2(100),
    monam1                      varchar2(100) Not Null,
    monam2                      varchar2(100) Not Null,
    monam3                      varchar2(100) Not Null,
    created_at                  TIMESTAMP  DEFAULT SYSDATE  NOT NULL ,
    created_by                  NUMBER,
    updated_at                  TIMESTAMP  DEFAULT SYSDATE  NOT NULL ,
    updated_by                  NUMBER,
    FOREIGN KEY (created_by) REFERENCES users(id),
    FOREIGN KEY (updated_by) REFERENCES users(id)
)
;
--done

create table requests_detials (
    req_id                    varchar2(36) PRIMARY KEY NOT NULL,
    id                          varchar2(36) Not Null,
    name1                 varchar2(10) Not Null,
    name2                 varchar2(10) Not Null,
    name3                 varchar2(10) Not Null,
    name4                 varchar2(10) Not Null,
    surname               varchar2(10),
    cat_Id                         varchar2(36) Not Null,
    birdate               TIMESTAMP Not Null,
    gen_id                         varchar2(36) Not Null,
    monam1                varchar2(10) Not Null,
    monam2                varchar2(10) Not Null,
    monam3                varchar2(10) Not Null,
    idnum                 varchar2(10) Not Null,
    iss_id1                         varchar2(36) Not Null,
    issdat1               date Not Null,
    natnam                 varchar2(100) Not Null,
    iss_id2                         varchar2(36) Not Null,
    issdat2               TIMESTAMP Not Null,
    pro_id                          varchar2(36) Not Null,
    addresses                   varchar2(100) Not Null,
    nearplace             varchar2(100) Not Null,
    mahala                varchar2(100) Not Null,
    zuqaq                 varchar2(100) Not Null,
    dar                   varchar2(100) Not Null,
    djp                   varchar2(100),
    numdet                varchar2(4000),
    datedet               TIMESTAMP,
    phone                 number Not Null,
    note                  varchar2(4000),
    created_at                     TIMESTAMP  DEFAULT SYSDATE  NOT NULL ,
    created_by                     NUMBER,
    updated_at                     TIMESTAMP  DEFAULT SYSDATE  NOT NULL ,
    updated_by                      NUMBER,
    FOREIGN KEY (created_by) REFERENCES users(id),
    FOREIGN KEY (updated_by) REFERENCES users(id),
    FOREIGN KEY (id) REFERENCES requests(id),
    FOREIGN KEY (cat_Id) REFERENCES Category(cat_Id),
     FOREIGN KEY (gen_id) REFERENCES gender(gen_id),
    FOREIGN KEY (iss_id1) REFERENCES Issuer(iss_id),
     FOREIGN KEY (iss_id2) REFERENCES Issuer(iss_id),
    FOREIGN KEY (pro_id) REFERENCES province(pro_id)
)
;
--nesreen

--done
create table information_person (
    info_id                        varchar2(36) PRIMARY KEY NOT NULL,
    name1                     varchar2(10) Not Null,
    name2                     varchar2(10) Not Null,
    name3                     varchar2(10) Not Null,
    name4                     varchar2(10) Not Null,
    surname                   varchar2(10),
    cat_Id                         varchar2(36) Not Null,
    papernum                  number Not Null,
    biom_id                        varchar2(36) Not Null,
    birdate                   TIMESTAMP Not Null,
    gen_id                         varchar2(36) Not Null,
    monam1                    varchar2(10) Not Null,
    monam2                    varchar2(10) Not Null,
    monam3                    varchar2(10) Not Null,
    idnum                     varchar2(10) Not Null,
    iss_id1                        varchar2(36) Not Null,
    issdat1                   TIMESTAMP Not Null,
    natnam                     varchar2(4000) Not Null,
    iss_id2                          varchar2(36) Not Null,
    issdat2                   TIMESTAMP Not Null,
    pro_id                        varchar2(36) Not Null,
    addresses                       varchar2(200) Not Null,
    nearplace                 varchar2(200) Not Null,
    mahala                    varchar2(200) Not Null,
    zuqaq                     varchar2(200) Not Null,
    dar                       varchar2(200) Not Null,
    djp                       varchar2(4000) Not Null,
    numdet                    varchar2(100) Not Null,
    datedet                  TIMESTAMP Not Null,
    phone                     number Not Null,
    status_boolean            varchar2(60),
    reason                    varchar2(4000),
    note                      varchar2(4000),
    case_boolean              varchar2(4000) Not Null,
    created_at                     TIMESTAMP  DEFAULT SYSDATE  NOT NULL ,
    created_by                     NUMBER,
    updated_at                     TIMESTAMP  DEFAULT SYSDATE  NOT NULL ,
    updated_by                      NUMBER,
    FOREIGN KEY (created_by) REFERENCES users(id),
    FOREIGN KEY (updated_by) REFERENCES users(id),
     FOREIGN KEY (cat_Id) REFERENCES Category(cat_Id),
    FOREIGN KEY (biom_id) REFERENCES biometric(biom_id),
     FOREIGN KEY (gen_id) REFERENCES gender(gen_id),
    FOREIGN KEY (iss_id1) REFERENCES Issuer(iss_id),
     FOREIGN KEY (iss_id2) REFERENCES Issuer(iss_id),
    FOREIGN KEY (pro_id) REFERENCES province(pro_id)
)
;

--done
create table biometric (
    biom_id                        varchar2(36) PRIMARY KEY NOT NULL,
    info_id                        varchar2(36) Not Null,
    pict                      number Not Null,
    iris                      number Not Null,
    fing                      number Not Null,
    note                      varchar2(4000),
    created_at                     TIMESTAMP  DEFAULT SYSDATE  NOT NULL ,
    created_by                     NUMBER,
    updated_at                     TIMESTAMP  DEFAULT SYSDATE  NOT NULL ,
    updated_by                      NUMBER,
    FOREIGN KEY (created_by) REFERENCES users(id),
    FOREIGN KEY (updated_by) REFERENCES users(id),
    FOREIGN KEY (info_id) REFERENCES information_person(info_id)

)
;
--done
create table weapon_table (
    weap_id                      varchar2(36) PRIMARY KEY NOT NULL,
    info_id                        varchar2(36) Not Null,
    req_id                        varchar2(36) Not Null,
    poss_id                       varchar2(36) Not Null,
    license_id                   varchar2(36) Not Null,
    weapon_name                  varchar2(100) Not Null,
    weanum1                 varchar2(100) Not Null,
    weapon_size                   varchar2(100) Not Null,
    datedet                 TIMESTAMP Not Null,
    status                  number(1),
    reason                  varchar2(4000),
    note                    varchar2(4000),
    created_at                     TIMESTAMP  DEFAULT SYSDATE  NOT NULL ,
    created_by                     NUMBER,
    updated_at                     TIMESTAMP  DEFAULT SYSDATE  NOT NULL ,
    updated_by                      NUMBER,
    FOREIGN KEY (created_by) REFERENCES users(id),
    FOREIGN KEY (updated_by) REFERENCES users(id),
    FOREIGN KEY (info_id) REFERENCES information_person(info_id),
    FOREIGN KEY (req_id) REFERENCES requests_detials(req_id),
    FOREIGN KEY (poss_id) REFERENCES Possession(poss_id),
    FOREIGN KEY (license_id) REFERENCES license_type(license_id),
    FOREIGN KEY (poss_id) REFERENCES weapon_name(weapon_id),
    FOREIGN KEY (license_id) REFERENCES weapon_name(weapon_id)

)
;
--done
create table Identification (
    ind_id                         varchar2(36) PRIMARY KEY NOT NULL,
    info_id                        varchar2(36) not null,
    weapon_id                      varchar2(36) not null,
    req_id                       varchar2(36) not null,
    printtime                  date not null,
    idnum                      number not null,
    expdate                    TIMESTAMP not null,
    permdate                   TIMESTAMP,
    note                       varchar2(4000) not null,
    created_at                     TIMESTAMP  DEFAULT SYSDATE  NOT NULL ,
    created_by                     NUMBER,
    updated_at                     TIMESTAMP  DEFAULT SYSDATE  NOT NULL ,
    updated_by                      NUMBER,
    FOREIGN KEY (created_by) REFERENCES users(id),
    FOREIGN KEY (updated_by) REFERENCES users(id),
    FOREIGN KEY (info_id) REFERENCES information_person(info_id),
    FOREIGN KEY (weapon_id) REFERENCES weapon_name(weapon_id),
    FOREIGN KEY (req_id) REFERENCES requests_detials(req_id)
)
;
--done
create table approval_details (
    app_id                      varchar2(36) PRIMARY KEY NOT NULL,
    info_id                        varchar2(36) not null,
    weapon_id                      varchar2(36) not null,
    apptype_id                     varchar2(36) not null,
    status                        number(1) not null,
    reason                       varchar2(4000),
    booknum                      varchar2(100),
    bookdate                     TIMESTAMP,
    note                          varchar2(4000),
    created_at                     TIMESTAMP  DEFAULT SYSDATE  NOT NULL ,
    created_by                     NUMBER,
    updated_at                     TIMESTAMP  DEFAULT SYSDATE  NOT NULL ,
    updated_by                      NUMBER,
    FOREIGN KEY (created_by) REFERENCES users(id),
    FOREIGN KEY (updated_by) REFERENCES users(id),
    FOREIGN KEY (info_id) REFERENCES information_person(info_id),
    FOREIGN KEY (weapon_id) REFERENCES weapon_name(weapon_id),
    FOREIGN KEY (apptype_id) REFERENCES approval_type(apptype_id)
)
;







